[32m2025-09-18 16:39:30 +0000[0m - dagster - [34mDEBUG[0m - run - 2140eddd-a73c-4eea-991a-6b14a472f259 - 148671 - LOGS_CAPTURED - Started capturing logs in process (pid: 148671).
[32m2025-09-18 16:39:30 +0000[0m - dagster - [34mDEBUG[0m - run - 2140eddd-a73c-4eea-991a-6b14a472f259 - 148671 - create_train_x - STEP_START - Started execution of step "create_train_x".
[32m2025-09-18 16:39:30 +0000[0m - dagster - [34mDEBUG[0m - run - 2140eddd-a73c-4eea-991a-6b14a472f259 - create_train_x - Loading file from: /workspaces/learning-mlops/part3/dagster_home/storage/storage/2140eddd-a73c-4eea-991a-6b14a472f259/read_dataframe/result using PickledObjectFilesystemIOManager...
[32m2025-09-18 16:39:30 +0000[0m - dagster - [34mDEBUG[0m - run - 2140eddd-a73c-4eea-991a-6b14a472f259 - 148671 - create_train_x - LOADED_INPUT - Loaded input "df" using input manager "io_manager", from output "result" of step "read_dataframe"
[32m2025-09-18 16:39:31 +0000[0m - dagster - [34mDEBUG[0m - run - 2140eddd-a73c-4eea-991a-6b14a472f259 - 148671 - create_train_x - STEP_INPUT - Got input "df" of type "DataFrame". (Type check passed).
[32m2025-09-18 16:39:31 +0000[0m - dagster - [34mDEBUG[0m - run - 2140eddd-a73c-4eea-991a-6b14a472f259 - 148671 - create_train_x - STEP_INPUT - Got input "dv" of type "Any". (Type check passed).
[32m2025-09-18 16:39:31 +0000[0m - dagster - [34mERROR[0m - [31mrun - 2140eddd-a73c-4eea-991a-6b14a472f259 - 148671 - create_train_x - STEP_FAILURE - Execution of step "create_train_x" failed.

dagster._core.errors.DagsterInvariantViolationError: op "create_train_x" has multiple outputs, but only one output was returned of type <class 'dict'>. When using multiple outputs, either yield each output, or return a tuple containing a value for each output. Check out the documentation on outputs for more: https://legacy-docs.dagster.io/concepts/ops-jobs-graphs/ops#outputs.

Stack Trace:
  File "/home/codespace/anaconda3/envs/mlops-part2-env/lib/python3.9/site-packages/dagster/_core/execution/plan/execute_plan.py", line 246, in dagster_event_sequence_for_step
    yield from check.generator(step_events)
  File "/home/codespace/anaconda3/envs/mlops-part2-env/lib/python3.9/site-packages/dagster/_core/execution/plan/execute_step.py", line 504, in core_dagster_event_sequence_for_step
    for user_event in _step_output_error_checked_user_event_sequence(
  File "/home/codespace/anaconda3/envs/mlops-part2-env/lib/python3.9/site-packages/dagster/_core/execution/plan/execute_step.py", line 183, in _step_output_error_checked_user_event_sequence
    for user_event in user_event_sequence:
  File "/home/codespace/anaconda3/envs/mlops-part2-env/lib/python3.9/site-packages/dagster/_core/execution/plan/execute_step.py", line 88, in _process_asset_results_to_events
    for user_event in user_event_sequence:
  File "/home/codespace/anaconda3/envs/mlops-part2-env/lib/python3.9/site-packages/dagster/_core/execution/plan/compute.py", line 190, in execute_core_compute
    for step_output in _yield_compute_results(step_context, inputs, compute_fn, compute_context):
  File "/home/codespace/anaconda3/envs/mlops-part2-env/lib/python3.9/site-packages/dagster/_core/execution/plan/compute.py", line 159, in _yield_compute_results
    for event in iterate_with_context(
  File "/home/codespace/anaconda3/envs/mlops-part2-env/lib/python3.9/site-packages/dagster/_utils/__init__.py", line 392, in iterate_with_context
    next_output = next(iterator)
  File "/home/codespace/anaconda3/envs/mlops-part2-env/lib/python3.9/site-packages/dagster/_core/execution/plan/compute_generator.py", line 140, in _coerce_op_compute_fn_to_iterator
    yield from validate_and_coerce_op_result_to_iterator(result, context, output_defs)
  File "/home/codespace/anaconda3/envs/mlops-part2-env/lib/python3.9/site-packages/dagster/_core/execution/plan/compute_generator.py", line 304, in validate_and_coerce_op_result_to_iterator
    for position, output_def, element in _zip_and_iterate_op_result(
  File "/home/codespace/anaconda3/envs/mlops-part2-env/lib/python3.9/site-packages/dagster/_core/execution/plan/compute_generator.py", line 161, in _zip_and_iterate_op_result
    result = _validate_multi_return(context, result, expected_return_outputs)
  File "/home/codespace/anaconda3/envs/mlops-part2-env/lib/python3.9/site-packages/dagster/_core/execution/plan/compute_generator.py", line 215, in _validate_multi_return
    raise DagsterInvariantViolationError(
[0m
