[32m2025-09-22 15:14:36 +0000[0m - dagster - [34mDEBUG[0m - run - d6a79b5a-0e1f-4041-bece-8bec53218488 - 78043 - LOGS_CAPTURED - Started capturing logs in process (pid: 78043).
[32m2025-09-22 15:14:36 +0000[0m - dagster - [34mDEBUG[0m - run - d6a79b5a-0e1f-4041-bece-8bec53218488 - 78043 - read_dataframe - STEP_START - Started execution of step "read_dataframe".
[32m2025-09-22 15:14:36 +0000[0m - dagster - [34mDEBUG[0m - run - d6a79b5a-0e1f-4041-bece-8bec53218488 - read_dataframe - Loading file from: /workspaces/learning-mlops/part3/dagster_home/storage/storage/d6a79b5a-0e1f-4041-bece-8bec53218488/get_year/result using PickledObjectFilesystemIOManager...
[32m2025-09-22 15:14:36 +0000[0m - dagster - [34mDEBUG[0m - run - d6a79b5a-0e1f-4041-bece-8bec53218488 - 78043 - read_dataframe - LOADED_INPUT - Loaded input "year" using input manager "io_manager", from output "result" of step "get_year"
[32m2025-09-22 15:14:36 +0000[0m - dagster - [34mDEBUG[0m - run - d6a79b5a-0e1f-4041-bece-8bec53218488 - read_dataframe - Loading file from: /workspaces/learning-mlops/part3/dagster_home/storage/storage/d6a79b5a-0e1f-4041-bece-8bec53218488/get_month/result using PickledObjectFilesystemIOManager...
[32m2025-09-22 15:14:36 +0000[0m - dagster - [34mDEBUG[0m - run - d6a79b5a-0e1f-4041-bece-8bec53218488 - 78043 - read_dataframe - LOADED_INPUT - Loaded input "month" using input manager "io_manager", from output "result" of step "get_month"
[32m2025-09-22 15:14:36 +0000[0m - dagster - [34mDEBUG[0m - run - d6a79b5a-0e1f-4041-bece-8bec53218488 - 78043 - read_dataframe - STEP_INPUT - Got input "year" of type "Int". (Type check passed).
[32m2025-09-22 15:14:36 +0000[0m - dagster - [34mDEBUG[0m - run - d6a79b5a-0e1f-4041-bece-8bec53218488 - 78043 - read_dataframe - STEP_INPUT - Got input "month" of type "Int". (Type check passed).
[32m2025-09-22 15:14:37 +0000[0m - dagster - [34mERROR[0m - [31mrun - d6a79b5a-0e1f-4041-bece-8bec53218488 - 78043 - read_dataframe - STEP_FAILURE - Execution of step "read_dataframe" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "read_dataframe"::

urllib.error.HTTPError: HTTP Error 403: Forbidden

Stack Trace:
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/dagster/_core/execution/plan/utils.py", line 57, in op_execution_error_boundary
    yield
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/dagster/_utils/__init__.py", line 392, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 137, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 117, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
                                                                    ^^^^^^^^^^^^^^^^^^
  File "/workspaces/learning-mlops/part3/dagster_home/../alt-workflow.py", line 37, in read_dataframe
    df = pd.read_parquet(url)
         ^^^^^^^^^^^^^^^^^^^^
  File "/home/codespace/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 669, in read_parquet
    return impl.read(
           ^^^^^^^^^^
  File "/home/codespace/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 258, in read
    path_or_handle, handles, filesystem = _get_path_or_handle(
                                          ^^^^^^^^^^^^^^^^^^^^
  File "/home/codespace/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 141, in _get_path_or_handle
    handles = get_handle(
              ^^^^^^^^^^^
  File "/home/codespace/.local/lib/python3.12/site-packages/pandas/io/common.py", line 728, in get_handle
    ioargs = _get_filepath_or_buffer(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codespace/.local/lib/python3.12/site-packages/pandas/io/common.py", line 384, in _get_filepath_or_buffer
    with urlopen(req_info) as req:
         ^^^^^^^^^^^^^^^^^
  File "/home/codespace/.local/lib/python3.12/site-packages/pandas/io/common.py", line 289, in urlopen
    return urllib.request.urlopen(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/urllib/request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/urllib/request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/urllib/request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/urllib/request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/urllib/request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
[0m
